service: cvs-tsk-atf-daily-schedules
useDotenv: true

package:
  individually: true
  exclude:
    - node_modules/**
    - .build/**
  include:
    - src/handler.ts

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

provider:
  profile: ${env:AWS_PROVIDER_PROFILE, 'default'}
  name: aws
  runtime: nodejs14.x
  stage: ${env:AWS_PROVIDER_STAGE, 'local'}
  region: ${env:AWS_PROVIDER_REGION, 'local'}
  # To load environment variables externally
  # rename env.example to .env.local
  # docs: https://github.com/serverless/serverless/blob/master/docs/providers/aws/guide/variables.md
  # we use dotenv, docs: https://github.com/colynb/serverless-dotenv-plugin
  environment:
    SERVICE_VERSION: ${env:API_VERSION}
    AWS_PROVIDER_REGION: ${self:provider.region}
    SERVICE: ${self:service}

functions:
  processWmsData:
    handler: src/handler.handler
    events:
      - http:
          path: process-wms-data
          method: get
      - cloudwatchEvent:
          event:
            source:
              - "aws.events"
            detail-type:
              - "Scheduled Event"
            detail:
              task:
                - "processWmsData"
      
custom:
  dotenv:
    basePath: './config/'
  webpack:
    webpackConfig: './scripts/webpack.config.js'
    keepOutputDirectory: false
    # can be toggled depending on env and .env files configuration
    includeModules: true # Node modules configuration for packaging, TBC whether we need the node_modules or 'inject' them when hosted on S3
    packager: 'npm' # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore
  # https://www.serverless.com/plugins/serverless-offline#usage-with-webpack - See Usage and command line options
  serverless-offline:
    httpPort: ${env:AWS_SERVER_PORT, 3001}
